package Solutions;

public class Solution_2 {
	public static void main(String args[]) {
		/*
		 * Each new term in the Fibonacci sequence is generated by adding the previous
		 * two terms. By starting with 1 and 2, the first 10 terms will be:
		 * 
		 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
		 * 
		 * By considering the terms in the Fibonacci sequence whose values do not exceed
		 * four million, find the sum of the even-valued terms.
		 */
		
		int prevNum = 0, nextNum = 1, fiboNum=0, result = 0;
		
		while(true) {
			fiboNum = prevNum + nextNum;
			prevNum = nextNum;
			nextNum = fiboNum;
			if(fiboNum > 400000)
				break;
			System.out.println("Fibo: "+fiboNum);
			 if(fiboNum%2 == 0) {
				 System.out.println("Even: "+nextNum);
				 result+=nextNum;
			 }
		}
		System.out.println("the sum of the even-valued terms: "+result);
	}

}
